### ISSUE TITLE
Installation requires libswscale-dev and libswresample-dev

### ISSUE THREAD

**Issue by jbarker-nvidia** [dukebw/lintel#2]
After building nasm, x264 and ffmpeg from source I was not able to install lintel through pip until I had installed libswscale-dev and libswresample-dev via apt.  It would be helpful to have these listed as prerequisites.

**Comment by dukebw** [comment]
Hi Jon, thanks for trying out the build process. Are you sure that libswscale and libswresample don't install along with FFmpeg? I guess you would have to set your environment variables to point to where libswscale.so and libswresample.so live.

Certainly I have built lintel on machines where I don't have sudo, and I don't recall doing anything special with these two libraries (besides installing FFmpeg from source).

**Comment by dukebw** [comment]
But I will think about using a VM to make a reproducible build process and to double-check your finding, when there is time.

**Comment by jbarker-nvidia** [comment]
Hi Brendan,  looks like I had a flag to my ffmpeg build that was disabling building swscale and swrescale - with that fixed they are there without manual apt install required.  Thanks for the heads up!
