### ISSUE TITLE
I am not quite sure on how to use for loading a video

### ISSUE THREAD

**Issue by ilan1987** [dukebw/lintel#29]
I read the instruction many times, I really wish to use this function:
decoded_frames = lintel.loadvid_frame_nums(video,frame_nums) . What I don't understand is what do you mean by encoded video? it is not working for 'video.mp4'. can you please explain how to load a video from a specific path?

**Comment by dukebw** [comment]
Hey, did you figure this out? The encoded video should be the actual video bytes (e.g., from calling `f = open('video.mp4', 'rb')` then `f.read()`.

**Comment by ilan1987** [comment]
@dukebw yes I got it. unfortunately, I found it 10% slower than opencv.

**Comment by dukebw** [comment]
Interesting, did you set `should_seek=True`?

**Comment by ilan1987** [comment]
Now that I did I get the only 2% slower. still slower than opencv.

**Comment by dukebw** [comment]
I see, thank you for checking. Would you mind sending me your snippet of code, and even if possible your video.mp4, so I can try to reproduce?
