### ISSUE TITLE
Error running lintel_test

### ISSUE THREAD

**Issue by jbarker-nvidia** [dukebw/lintel#3]
When running `lintel_test --filename <filename> --width <width> --height <height>` on a 540p .mp4 file I get the following error:

`SystemError: <built-in function loadvid> returned NULL without setting an error`

I also get this error if I use the `_load_video_to_4darray` or `_load_frame_nums_to_4darray` samples provided.

**Comment by dukebw** [comment]
Are you passing the correct width and height for the video? I.e., the same width and height that would be returned by ffprobe.

**Comment by jbarker-nvidia** [comment]
I was, but that's not the issue.  It seems the problem was not adding my ffmpeg/nasm/x264 build locations to one of my environment variables.  lintel must have been unable to find one of them.  All working now!
