### ISSUE TITLE
set 'should_random_seek' False.

### ISSUE THREAD

**Issue by dihuangcode** [dukebw/lintel#32]
Thx for your  awesome work
What if I set 'should_random_seek' false, will I get the middle part of the video or something else?

**Comment by dukebw** [comment]
Hi there. If `should_random_seek` is false, Lintel just decodes from the first frame of the video. For a more general API I would suggest using `lintel.loadvid_frame_nums`.

**Comment by dihuangcode** [comment]
There is no API to get frame number of video directly.  So if I want to get frames at equal intervals, there doesn't seem to be a suitable way.

**Comment by dihuangcode** [comment]
`cv2.VideoCapture()` solve this problem
